# theme = "gruvbox_dark_hard"
# theme = "molokai"
theme = "dark_plus" # vscode color scheme

[editor]
true-color = true
line-number = "relative"
cursorline = true
# cursorcolumn = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["version-control", "diagnostics", "register", "position", "file-encoding"]

[editor.indent-guides]
render = true

[keys.insert]
"C-c" = ["collapse_selection", "normal_mode"]
"C-n" = "completion"
"C-7" = "toggle_comments" # ctrl + /
"A-h" = "move_char_left"
"A-j" = "move_visual_line_down"
"A-k" = "move_visual_line_up"
"A-l" = "move_char_right"
"A-w" = "move_next_word_start"
"A-b" = "move_prev_word_start"

[keys.select]
"C-c" = ["collapse_selection", "normal_mode"]
esc = ["collapse_selection", "normal_mode"]
"C-7" = "toggle_comments" # ctrl + /

[keys.normal]
"$" = "goto_line_end"
"G" = "goto_file_end"
esc = ["collapse_selection", "keep_primary_selection"]
"C-c" = ["collapse_selection", "keep_primary_selection"]
"C-7" = "toggle_comments" # ctrl + /

