theme = "gruvbox_dark_hard"
# theme = "molokai"
# theme = "dark_plus" # vscode color scheme

[editor]
true-color = true
line-number = "relative"
cursorline = true
# cursorcolumn = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["version-control", "diagnostics", "register", "position", "file-encoding"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "all"

[keys.insert]
"C-c" = ["collapse_selection", "normal_mode"]
"C-n" = "completion"
"C-7" = "toggle_comments" # ctrl + /
"A-h" = "move_char_left"
"A-j" = "move_visual_line_down"
"A-k" = "move_visual_line_up"
"A-l" = "move_char_right"
"A-w" = ["move_next_word_start", "collapse_selection"]
"A-b" = ["move_prev_word_start", "collapse_selection"]

[keys.select]
"C-c" = ["collapse_selection", "normal_mode"]
esc = ["collapse_selection", "normal_mode"]
"C-7" = "toggle_comments" # ctrl + /
"$" = "goto_line_end"
"G" = "goto_file_end"
"^" = "goto_first_nonwhitespace"
"0" = "goto_line_start"

[keys.normal]
"$" = "goto_line_end"
"G" = "goto_file_end"
"^" = "goto_first_nonwhitespace"
"0" = "goto_line_start"
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
esc = ["collapse_selection", "keep_primary_selection"]
"C-c" = ["collapse_selection", "keep_primary_selection"]
"C-7" = "toggle_comments" # ctrl + /

