[[language]]
name = "markdown"
language-servers = ["marksman"]

[language.auto-pairs]
'(' = ')'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'*' = '*'
'_' = '_'

[[language]]
name = "nix"
language-servers = ["nil", "nixd"]

[[language]]
name = "bash"
language-servers = ["bash-language-server"]

[[language]]
name = "python"
language-servers = ["ty", "ruff", "jedi", "pylsp"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp"]

[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "ansible-language-server"]
