# Author : Carter Watson <github.com/cartwatson>
# The theme uses the gruvbox light palette with hard contrast: github.com/morhetz/gruvbox

inherits = "gruvbox_light_hard"

"ui.text.focus" = { fg = "green1", bg="bg1" }
"ui.menu.selected" = { fg = "green1", bg = "bg1", modifiers = ["bold"] }
