# Author : Carter Watson <github.com/cartwatson>
# The theme uses the gruvbox light palette with hard contrast: github.com/morhetz/gruvbox

inherits = "gruvbox_light_hard"

# "ui.text.focus" = { fg = "green1" } # current
"ui.text.focus" = { bg="bg1" }

