# .sops.yaml

keys:
  - &jupiter_cwatson age1j93ahd5wrea7hwp5nrvg6qd0m06kzq4h45lmhjm6mk42xmtm556qra73ad
creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
    - age:
      - *jupiter_cwatson
