# .sops.yaml

keys:
  - &jupiter_cwatson age1j93ahd5wrea7hwp5nrvg6qd0m06kzq4h45lmhjm6mk42xmtm556qra73ad
  - &nova_cwatson age1arp89zedg00jeas2fzeq7szcpldwnslpp24ew3mr4tnfur0q8qrsh97muh
  - &eclipse_cwatson age19w4rh5lvc4wjnksljvkp733pgnydtm4pk43prwdemklrd4ryxccqrgpj3u
  - &saturn_varlib age1s35qz9phpew20dnesamndxmmxx097gx8rlhwgtarquc59pjfjdjq7sr0e5
  - &kuiper_varlib age18f6nm2nqs9ntz0c6604pntffcyhpzmsxgn2d2e3f9ay0x3mk8g8s6yrpzg
creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
    - age:
      - *jupiter_cwatson
      - *nova_cwatson
      - *eclipse_cwatson
      - *saturn_varlib
      - *kuiper_varlib
