# Gruvbox Tmux Colorscheme
# author: https://github.com/cartwatson
# original author: https://github.com/egel/tmux-gruvbox/

# gruvbox theme
set -g @bg1 "#4e4e4e" # default background
set -g @bg2 "#3a3a3a" # inside panels
set -g @bg3 "#1c1c1c" # outside most panels
set -g @fg1 "#ebdbb2" # off-white for gray background
set -g @fg2 "#282828" # gray foreground for orange background

## highlights
set -g @yellow "#d79921"
set -g @red    "#cc241d"
set -g @green  "#98971a"
set -g @purple "#b16286"
set -g @blue   "#458488"
set -g @orange "#d86d0e"
set -g @gray   "#928374"

set -g @active "#{@yellow}"

# pane number display
# WARN WARN WARN: colors here cannot be variables, the above are tmux "styles" and these are required to be "colours"
set-option -g display-panes-active-colour "#d79921" #active - yellow
set-option -g display-panes-colour        "#b16286" #purple

## Theme settings mixed with colors
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

# default statusbar color
set-option -g status-style "bg=#{@bg1},fg=#{@fg1}"

# pane border
set-option -g pane-active-border-style "fg=#{E:#{@active}}"
set-option -g pane-border-style "fg=#{@bg1}"

# message infos
set-option -g message-style "bg=#{@purple},fg=#{@fg1}"

# writing commands inactive
set-option -g message-command-style "bg=#{@purple},fg=#{@fg1}"

# selection when in copy paste mode, and prefix+s selection
set-option -g mode-style "bg=#{E:#{@active}},fg=#{@fg2}"

# display
# - session name
# - prefix indicator (gray at rest, orange while prefix key is active)
set -g @session_name "#[bg=#{@bg3},fg=#{@fg1}] #S "
set -g @prefix_ind   "#{?client_prefix,#[bg=#{@gray}#,fg=#{@fg2}] ,#[bg=#{@orange}#,fg=#{@fg2}] }"
set-option -g status-left "#{E:#{@session_name}}#{E:#{@prefix_ind}}"

# - battery (if present)
#   - blue   = normal
#   - green  = charging
#   - red    = crit <=10%
#   - orange = low  <=20%
set -g @battery "#{?#(acpi -b 2>/dev/null),\
#{?#(acpi -a 2>/dev/null | grep -q on && echo 1),#[bg=#{@green}],\
#{?#(acpi -b 2>/dev/null | grep -o '[0-9]*%' | tr -d '%' | grep -qE '^[0-9]$|^10$' && echo 1),#[bg=#{@red}],\
#{?#(acpi -b 2>/dev/null | grep -o '[0-9]*%' | tr -d '%' | grep -qE '^[0-9]$|^1[0-9]$|^20$' && echo 1),#[bg=#{@orange}],#[bg=#{@blue}]}}}\
#[fg=#{@fg1}] #(acpi -b | grep -o '[0-9]*%') ,}"
set -g @hostname_str "#[bg=#{@purple},fg=#{@fg1}] #h "
set -g @timestamp "#[bg=#{@bg3},fg=#{@fg1}] %Y-%m-%dT%H:%M "

set-option -g status-right "#{E:#{@battery}}#{E:#{@hostname_str}}#{E:#{@timestamp}}"

# format + color for window selection aspect of status bar
# '#I' is window number
# '#W' is window title
set-window-option -g window-status-current-format "#[bg=#{E:#{@active}},fg=#{@fg2}] #I #W #{?window_zoomed_flag,*Z ,}"
set-window-option -g window-status-format         "#[bg=#{@bg2},fg=#{@fg1}] #I #W "

